### ISSUE TITLE
Zabbix vs Prometheus

### ISSUE THREAD

**Issue by AleksDolgop** [ilink-pro/devops#5]
Что лучше использовать для мониторинга забикс или прометей и почему?
Забикс много всего из коробки имеет, прометей еще настраивать надо + графану накидывать

**Comment by TorinAsakura** [comment]
# Общие отличия
В Prometheus и его стеке тебе надо собирать всё самому, с одной стороны увеличивается порог входа, с другой достигается эффективность работы при использовании данного инструмента, так как у тебя будет только то, что тебе действительно нужно и тебе не придётся разбираться в тонне "готовых" надстроек Zabbix.

У Zabbix всё есть "из коробки" и вот тут вообще не нужно париться, другой вопрос, что этим нужно уметь пользоваться.

# Zabbix
- Как я уже писал выше у него все инструменты мониторинга готовы к работе уже при сетапе
- Это не только мониторинг, это хранение и логирование, события, логи, журналы и всё это он может хранить в текстовом виде
- Про системный мониторинг общего назначения, хранение данных об инцидентах, однако одно из слабых мест Zabbix - база и там нужно будет серьёзно корпеть над оптимизацией, так как из коробки "оптимизаторов" нет, там правда не так давно завезли PSQL+TSDB но апи до всех пор всё ещё сырое
- Выборки делаются тупо через SQL
- Не подходит для нормальный работы с k8s/k3s
- Для интеграции с third-party нужно писать громоздкие шаблоны в духе Apache Velocity

# Prometheus
- Ничего нет, надо использовать Grafana, однако она куда мощнее, быстрее и удобнее чем готовые решения Zabbix
- В отличие от Zabbix работает только с временными рядами, если нужно что-то хранить и складировать можно брать TSDB, он отлично оптимизирован под временные ряды и добавление данных по принципу pull, можно сказать, что эта штука для оперативного мониторинга, чего не скажешь про Zabbix. Однако если надо хранить данные длительное время, для этих целей Prometheus не подойдёт
- Опять же, он про оперативное реагирование и отслеживание инцидентов, а не для хранение и анализа этих данных, однако алёрты нужно будет настраивать отдельно в Aletsmanager, это тоже утилита из их экосистемы
- Есть свой QL - можно делать сложные выборки легко и быстро
- Service Discovery - сам находит таргеты и ставит их на мониторинг
- Exporters - многие third-party работают из коробки

# Подытоживая
- Если говорить простым языком то: Zabbix для ленивых, а Prometheus для пытливых
- Zabbix - тема для олдскульных "старожил" сис. админов, где тебе, также как и в Gitlab предлагают многое из коробки, однако, если тебе потребуется что-то "своё" то вот тут начинаются анальные утехи
- Prometheus это типа фреймворка - собирай что хочешь, никаких ограничений и вендорлоков
- Prometheus предназначен для динамических систем k8s/k3s
- Zabbix предназначен для "классических" архитектур и для кубера и прочих толком не подходит и для его настройки под кубер уходит гигантское количество времени не говоря уже про поддержку
